### ISSUE TITLE
Invalid entities in the Vaccum Map Card

### ISSUE THREAD

**Issue by nerdinary** [bfg100k/Viomi-S9-HA-Integration#1]
Firstly, thanks so much for putting together this repo and guide. I've had a Viomi S9 for the longest time and almost gave up on integrating it with HA.

I've followed your steps in the guide and it looks like some entities you're referencing don't seem to exist:

```
Invalid entities:

    select.viomi_v18_155a_clean_mode

    select.viomi_v18_155a_mopping_mode

    sensor.viomi_v18_155a_clean_time

```

Are these entities that you manually created?

**Comment by bfg100k** [comment]
No. They were created by the MIOT integration. Which integration are you using?

**Comment by nerdinary** [comment]
I'm using the miot integration as well - same as the one linked from your guide. 
I've deleted the integration and forced it to recreate the entities, but those three entries still don't show up. Odd

**Comment by bfg100k** [comment]
what is the viomi device spec detected in the integration? i.e. is it viomi_v18? Can you list the entities in your setup?

**Comment by nerdinary** [comment]
Here is what I have.

Device: `viomi.vacuum.v18`
Firmware: `1.6.5_2254 `

Here are the entities (25 of them)

```
sensor.viomi_v18_155a_battery_level
vacuum.viomi_v18_155a_robot_cleaner
sensor.viomi_v18_155a_device_fault
sensor.viomi_v18_155a_door_state
number.viomi_v18_155a_mute
sensor.viomi_v18_155a_status
select.viomi_v18_155a_sweep_type
select.viomi_v18_155a_wide_dynamic_range_mode
switch.viomi_v18_155a_dust_collection
sensor.viomi_v18_155a_hypa_hours
sensor.viomi_v18_155a_hypa_life
select.viomi_v18_155a_mop_route
switch.viomi_v18_155a_remember_state
switch.viomi_v18_155a_repeat_state
sensor.viomi_v18_155a_main_brush_hours
sensor.viomi_v18_155a_main_brush_life
select.viomi_v18_155a_water_grade
sensor.viomi_v18_155a_mop_hours
sensor.viomi_v18_155a_mop_life
sensor.viomi_v18_155a_clean_use_time
sensor.viomi_v18_155a_clean_area
sensor.viomi_v18_155a_side_brush_hours
sensor.viomi_v18_155a_side_brush_life
sensor.mi_1676003610_message
sensor.mi_1676003610_244001062730_scene_history
```

**Comment by nerdinary** [comment]
Update: I figured it out. For some reason, those three entities are named differently on my device. Here is what they map to:

| Yours  | Mine   |
|---|---|
|     select.viomi_v18_155a_clean_mode  | select.viomi_v18_155a_wide_dynamic_range_mode   | 
|     select.viomi_v18_155a_mopping_mode   |      select.viomi_v18_155a_mop_route | 
|      sensor.viomi_v18_155a_clean_time  |      sensor.viomi_v18_155a_clean_use_time |

One I replaced the entities in your card with the mapping above, it works!

**Comment by bfg100k** [comment]
Looks like the MIOT integration has renamed those entities in an update since the time I set my device up. I will update my code to reflect this.
